codecov:
  notify:
    after_n_builds: 3
coverage:
  status:
    project:
      default:
        target: auto
        # this allows a 1% drop from the previous base commit coverage
        threshold: 2%
  # makes it so that unit, cy ct and cy e2e reports finish running before the report is shown in a PAR
  # https://docs.codecov.com/docs/notifications#preventing-notifications-until-after-n-builds
  ignore:
    - 'src/**/*.cy.js'
    - 'src/**/*.test.js'
    - 'src/**/regex.js'
    - 'src/**/reducer.js'
    - 'src/**/useFetch.js'
    - 'src/**/weekReducer.js'
    - 'src/**/ErrorBoundary.js'
