import './UI/pageSpinner.cy'
import './UI/errorComp.cy'
import './UI/spinner.cy'
import './Bookings/bookings.cy'
import './Bookings/booking.cy'
import './Bookings/bookingDetails.cy'
import './Bookings/bookingsGrid.cy'
import './Bookings/WeekPicker.cy'
import './Bookings/BookingsPage.cy'
import './Bookings/bookingForm.cy'
import './Bookables/bookableForm.cy'
import './Bookables/bookableDetails.cy'
import './Bookables/bookableEdit.cy'
import './Bookables/BookablesList.cy'
import './Bookables/bookablenew.cy'
import './Bookables/bookablesView.cy'
import './Users/userDetails.cy'
import './Users/avatar.cy'
import './Users/UsersList.cy'
import './Users/userPicker.cy'
import './Users/usersPage.cy'

// find . -type f | grep cy.js
// https://glebbahmutov.com/blog/run-all-specs-cypress-v10/
