# https://github.com/bahmutov/test-todomvc-using-app-actions/blob/master/.github/workflows/repeat-test.yml

name: repeat-spec
on:
  workflow_dispatch:
    description: Lets the user run a spec file N times in a row
    inputs:
      title:
        description: any string in a describe or it block title
        required: true
        type: string
      n:
        description: Number of times to repeat the test
        required: false
        default: '1'
        type: string

jobs:
  repeat-spec:
    runs-on: ubuntu-20.04
    steps:
      - name: Print workflow inputs
        run: |
          echo Running tests with title: ${{ github.event.inputs.title }}
          echo for ${{ github.event.inputs.n }} times

      - name: Checkout 🛎
        uses: actions/checkout@v3

      # https://github.com/cypress-io/github-action
      - name: Run the spec N times
        uses: cypress-io/github-action@v3
        with:
          start: yarn start
          wait-on: 'http://localhost:3000'
          browser: chrome
          env: 'grep="${{ github.event.inputs.title }}",burn=${{ github.event.inputs.n }},grepFilterSpecs=true,grepOmitFiltered=true'
