# https://github.com/bahmutov/test-todomvc-using-app-actions/blob/master/.github/workflows/repeat-test.yml

name: repeat-spec
on:
  workflow_dispatch:
    description: Lets the user run a spec file N times in a row
    inputs:
      title:
        description: any string in a describe or it block title
        required: false
        type: string
      tag:
        description: Tag to run
        required: false
        type: string
      n:
        description: Number of times to repeat the test
        required: false
        default: 1
        type: integer

jobs:
  repeat-spec:
    runs-on: ubuntu-20.04
    steps:
      - name: Print workflow inputs
        run: |
          echo Running the spec file "${{ github.event.inputs.spec }}"
          echo for ${{ github.event.inputs.n }} times

      - name: Checkout 🛎
        uses: actions/checkout@v2

      # https://github.com/cypress-io/github-action
      - name: Run the spec N times
        uses: cypress-io/github-action@v3
        with:
          start: yarn start
          wait-on: 'http://localhost:3000'
          browser: chrome
          env: 'grep="${{ github.event.inputs.title }}",grepTags=${{ github.event.inputs.tag}},burn=${{ github.event.inputs.n }},grepFilterSpecs=true'
        #   record: true
        #   parallel: true
        #   group: e2e-tests
        #   tag: e2e-tests
        # env:
        #   CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
